-- DROP TYPE
DROP TYPE IF EXISTS Region CASCADE; 
DROP TYPE IF EXISTS Month CASCADE;
DROP TYPE IF EXISTS UnitType CASCADE; 
DROP TYPE IF EXISTS RoomType CASCADE; 
DROP TYPE IF EXISTS RoomSize CASCADE; 
DROP TYPE IF EXISTS HandlerType CASCADE;
DROP TYPE IF EXISTS MobileNumberType CASCADE;
DROP TYPE IF EXISTS AccommodationType CASCADE;

-- DROP TABLE
DROP TABLE IF EXISTS visitor CASCADE;
DROP TABLE IF EXISTS handler CASCADE;
DROP TABLE IF EXISTS email CASCADE;
DROP TABLE IF EXISTS mobile_number CASCADE;
DROP TABLE IF EXISTS time_scrap CASCADE;
DROP TABLE IF EXISTS accommodation CASCADE;
DROP TABLE IF EXISTS unit CASCADE;
DROP TABLE IF EXISTS room CASCADE;
DROP TABLE IF EXISTS room_capacity CASCADE;
DROP TABLE IF EXISTS unit_rating CASCADE;
DROP TABLE IF EXISTS unit_bookmarked CASCADE;
DROP TABLE IF EXISTS unit_visit CASCADE;
DROP TABLE IF EXISTS room CASCADE;
DROP TABLE IF EXISTS room_rating CASCADE;
DROP TABLE IF EXISTS room_bookmarked CASCADE;
DROP TABLE IF EXISTS room_visit CASCADE;
DROP TABLE IF EXISTS utari_user CASCADE;
