name: server-ci-cd

on: [push, pull_request]

env:
    IS_CI: true

jobs:
    all:
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
            matrix:
                threads:
                    - '4'
        steps:
            - name: Checkout Code
              uses: actions/checkout@v2

            - name: Install and Setup PostgreSQL
              run: make install-postgresql
                  && make setup-postgresql

            - name: Install Depedencies
              run: make install

            - name: Create Views and Functions
              run: mkdir temp && make create

            - name: Run PgTyped
              env:
                  PGUSER: postgres
                  PGHOST: localhost
                  PGDATABASE: utari
                  PGPASSWORD: postgres
                  PGPORT: 5432
              run: make pg-gen

            - name: Run Linter
              run: make lint

            - name: Run Typecheck
              run: make typecheck

            - name: Run Format Check
              run: make format-check

            - name: Run Tests
              env:
                  NODE_ENV: test
                  PGUSER: postgres
                  PGHOST: localhost
                  PGDATABASE: test
                  PGPASSWORD: postgres
                  PGPORT: 5432
                  MAPS_API_KEY: ${{ secrets.MAPS_API_KEY }}
              run: |
                  make test
                  rm -rf __tests__

            - name: Run Build
              # just to ensure build dont fail due to absence of env variable
              # the real env will be used somewhere else
              env:
                  NODE_ENV: production
                  ORIGIN: origin
                  PGUSER: postgres
                  PGHOST: localhost
                  PGDATABASE: test
                  PGPASSWORD: postgres
                  PGPORT: 5432
                  MAPS_API_KEY: api
                  EMAIL: email
                  PASS: pass
                  FIREBASE_TYPE: type
                  FIREBASE_KEY: key
                  FIREBASE_PROJECT_ID: id
                  FIREBASE_KEY_ID: id
                  FIREBASE_CLIENT_EMAIL: email
                  FIREBASE_CLIENT_ID: id
                  FIREBASE_AUTH_URI: uri
                  FIREBASE_TOKEN_URI: uri
                  FIREBASE_AUTH_PROVIDER_X509_CERT_URL: url
                  FIREBASE_CLIENT_X509_CERT_URL: url
                  DATABASE_URL: url
              run: make build
