name: server-ci-cd

on: [push, pull_request]

jobs:
    all:
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
            matrix:
                threads:
                    - '4'
        steps:
            - name: Checkout Code
              uses: actions/checkout@v2

            - name: Install and Setup PostgreSQL
              run: |
                  make install
                  make setup

            - name: Install Depedencies
              run: yarn

            - name: Run PgTyped
              env:
                  PGUSER: postgres
                  PGHOST: localhost
                  PGDATABASE: utari
                  PGPASSWORD: postgres
                  PGPORT: 5432
              run: make pg-gen

            - name: Run Linter
              run: make lint-src

            - name: Run Typecheck
              run: make typecheck

            - name: Run Format Check
              run: make format-check

            - name: Run Tests
              env:
                  NODE_ENV: test
                  PGUSER: postgres
                  PGHOST: localhost
                  PGTESTDATABASE: test
                  PGPASSWORD: postgres
                  PGPORT: 5432
                  MAPS_API_KEY: ${{ secrets.MAPS_API_KEY }}
              run: |
                  make test
                  rm -rf __tests__

            - name: Run Build
              run: make build
